
-- liquibase formatted sql

-- changeset liquibase:2
CREATE TABLE author
(
    id NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1
        PRIMARY KEY,
    first_name VARCHAR2( 255 ) NOT NULL,
    last_name VARCHAR2( 255 ) NOT NULL
);
