
-- liquibase formatted sql

-- changeset liquibase:3
CREATE TABLE post
(
    id NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1
        PRIMARY KEY,
    title VARCHAR2( 255 ) NOT NULL,
    body VARCHAR2( 255 ) NOT NULL,
    created_on date,
    author_id number,
    CONSTRAINT fk_auth
        FOREIGN KEY (author_id)
            REFERENCES author(id)
);
