
-- liquibase formatted sql

-- changeset liquibase:1
CREATE TABLE product_categories
(
    category_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 6
        PRIMARY KEY,
    category_name VARCHAR2( 255 ) NOT NULL
);
